#-----| GUI and Style
# Just a section dedicated to your stylization of the GUI
# There's nothing really that fancy for now.
Colors:
  primary_color: "#e8d500"
  secondary_color: "#e8a200"

#-----| Support Groups
# By default, each new Ticket will be created with a "default"
# group. Theses are YOUR custom groups that those "default"
# tickets can get sorted into. Sorting into a group will enable
# ticket notifications (if enabled) for users who have that group.
#
# DO NOT USE SPACES! USE UNDERSCORES! The plugin converts these names
# for permission groups directly! "Two Groups" -> "two_groups"
#
# Limit for Support Groups is 9! Anything after that is getting nuked.
#
# To assign a user to a support group, use permission `ticket.group.<name>'
Support Groups:
  - mods
  - devs
  - admins
  - silly_geese

Ticket Notifications: true

#-----| Overrides
#
# Set your default world in case a teleport world location returns null:
default world: "world"