name: OpenTickets
version: '${version}'
main: dev.arcticgaming.opentickets.OpenTickets
api-version: '1.20'
authors: [ ArcticDev_ ]
description: An open-sourced Minecraft Ticket Plugin
commands:
  tickets:
    description: main command starter