name: OpenTickets
version: '${project.version}'
main: dev.arcticgaming.opentickets.OpenTickets
api-version: 1.19
authors: [ ArcticDev_ ]
description: An open-sourced Minecraft Ticket Plugin
commands:
  createTicket:
    description: creates a new ticket!
  viewTickets:
    description: opens Ticket Viewer!
    permissions: "opentickets.admin"